#!/bin/bash

# shellcheck source=boot-starter.conf

if [ -f ./boot-starter.conf ]; then
    source boot-starter.conf
else
    echo '未找到 boot-starter.conf'
    exit 1
fi

printGreen() {
    echo -ne "\e[32m$*\e[0m"
}
printRed() {
    echo -ne "\e[31m$*\e[0m"
}

exeShell() {
    printGreen "$1\n$2" 1>&2
    local shell
    shell=$(echo -e "$1" | tr -d '\n')
    eval "$shell"
}

# 查询监听在某一端口的程序pid
findPidListenedOnPort() {
    ss -lp sport eq "$1" |
        grep -Eo ',pid=[0-9]{1,7},' |
        grep -Eo '[0-9]+' |
        head -1
}

waitListenOnPort() {
    while [ ! "$(findPidListenedOnPort $1)" ]; do
        printGreen .
        sleep 1s
    done
}

killProcess() {
    kill -15 "$1"
}

startBoot() {
    exeShell "$start_shell_perfix$1$start_shell_suffix"
}

stopBoot() {
    local opid
    opid=$(findPidListenedOnPort "$1")
    if [ "$opid" ]; then
        printRed "等待 $opid 进程关闭。$1 端口\n"
        killProcess "$opid"
    else
        printRed "没有程序监听 $1 端口\n"
    fi
}

start() {
    printGreen "项目启动中...\n"
    if [ ! "$use_systemd" ]; then
        startBoot "${ports[$1]}"
    else
        exeShell "$systemd_command start ${systemd_services[$1]}"
    fi
}

restart() {
    local opid
    local index
    for ((index = 0; index < ${#ports[@]}; index++)); do
        opid=$(findPidListenedOnPort "${ports[$index]}")
        if [ "$opid" ]; then
            break
        fi
    done
    if [ ! "$opid" ]; then
        index=0
    fi
    if [ ! "$use_systemd" ]; then
        if [ "$opid" ]; then
            stopBoot "${ports[$index]}"
        fi
        startBoot "${ports[$index]}"
    else
        exeShell "$systemd_command restart ${systemd_services[$index]}"
    fi
}

stop() {
    if [ ! "$use_systemd" ]; then
        stopBoot "${ports[0]}"
        stopBoot "${ports[1]}"
    else
        exeShell "$systemd_command stop ${systemd_services[*]}"
    fi
}

status() {
    local opid
    local checkedPort
    for port in "${ports[@]}"; do
        checkedPort=$port
        opid=$(findPidListenedOnPort "$port")
        if [ "$opid" ]; then
            break
        fi
    done
    if [ "$opid" ]; then
        printGreen "$opid 进程已经监听 $checkedPort 端口\n"
    else
        printGreen "项目没有启动\n"
    fi
}

deployer() {
    start "$1"
    printGreen "等待监听 ${ports[$1]} 端口\n"
    waitListenOnPort "$1"
    echo ""
    sleep 5s
    stopBoot "$2"
}

deploy() {
    local opid
    opid=$(findPidListenedOnPort "${ports[0]}")
    if [ "$opid" ]; then
        deployer 1 0
    else
        deployer 0 1
    fi
}

printHelp() {
    printGreen "start 启动项目; stop 关闭项目\n"
}

case "$1" in
"deploy")
    deploy
    ;;
"restart")
    restart
    ;;
"stop")
    stop
    ;;
"status")
    status
    ;;
*)
    printHelp
    ;;
esac
